# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SRCNN-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SRCNN-ios

end

target 'SRCNNKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SRCNNKit
  #pod 'CoreMLHelpers', :git => 'git@github.com:hollance/CoreMLHelpers.git'

end
